apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notes-backend
  template:
    metadata:
      labels:
        app: notes-backend
    spec:
      containers:
      - name: notes-backend
        image: djahongir/notes-backend:latest  # Jenkins push qilgan image
        imagePullPolicy: Always 
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URL
          value: "mongodb://mongo:27017"
---
apiVersion: v1
kind: Service
metadata:
  name: notes-backend
spec:
  selector:
    app: notes-backend
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP
